"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import microbitAnim
import json

# Implementing MyFrame1
class MyProject1MyFrame1( microbitAnim.MyFrame1 ):
    def __init__( self, parent ):
        microbitAnim.MyFrame1.__init__( self, parent )

    # Handlers for MyFrame1 events.
    def onButton00Click( self, event ):
        if (self.m_button00.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button00.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button00.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()
    
    def onButton01Click( self, event ):
        if (self.m_button01.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button01.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button01.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton02Click( self, event ):
        if (self.m_button02.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button02.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button02.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton03Click( self, event ):
        if (self.m_button03.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button03.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button03.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton04Click( self, event ):
        if (self.m_button04.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button04.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button04.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()


###
    def onButton10Click( self, event ):
        if (self.m_button10.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button10.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button10.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()
    
    def onButton11Click( self, event ):
        if (self.m_button11.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button11.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button11.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton12Click( self, event ):
        if (self.m_button12.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button12.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button12.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton13Click( self, event ):
        if (self.m_button13.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button13.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button13.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton14Click( self, event ):
        if (self.m_button14.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button14.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button14.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()
###
    def onButton20Click( self, event ):
        if (self.m_button20.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button20.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button20.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()
    
    def onButton21Click( self, event ):
        if (self.m_button21.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button21.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button21.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton22Click( self, event ):
        if (self.m_button22.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button22.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button22.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton23Click( self, event ):
        if (self.m_button23.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button23.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button23.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton24Click( self, event ):
        if (self.m_button24.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button24.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button24.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()
###
    def onButton30Click( self, event ):
        if (self.m_button30.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button30.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button30.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()
    
    def onButton31Click( self, event ):
        if (self.m_button31.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button31.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button31.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton32Click( self, event ):
        if (self.m_button32.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button32.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button32.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton33Click( self, event ):
        if (self.m_button33.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button33.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button33.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton34Click( self, event ):
        if (self.m_button34.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button34.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button34.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()
###
    def onButton40Click( self, event ):
        if (self.m_button40.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button40.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button40.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()
    
    def onButton41Click( self, event ):
        if (self.m_button41.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button41.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button41.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton42Click( self, event ):
        if (self.m_button42.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button42.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button42.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton43Click( self, event ):
        if (self.m_button43.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button43.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button43.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton44Click( self, event ):
        if (self.m_button44.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button44.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button44.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()
    
    def getDisplayString( self ):
        s = [
            ['0','0','0','0','0'],
            ['0','0','0','0','0'],
            ['0','0','0','0','0'],
            ['0','0','0','0','0'],
            ['0','0','0','0','0']
        ]
        if (self.m_button00.BackgroundColour == wx.Colour( 255, 0, 0 )): s[0][0] = '6'
        if (self.m_button01.BackgroundColour == wx.Colour( 255, 0, 0 )): s[0][1] = '6'
        if (self.m_button02.BackgroundColour == wx.Colour( 255, 0, 0 )): s[0][2] = '6'
        if (self.m_button03.BackgroundColour == wx.Colour( 255, 0, 0 )): s[0][3] = '6'
        if (self.m_button04.BackgroundColour == wx.Colour( 255, 0, 0 )): s[0][4] = '6'

        if (self.m_button10.BackgroundColour == wx.Colour( 255, 0, 0 )): s[1][0] = '6'
        if (self.m_button11.BackgroundColour == wx.Colour( 255, 0, 0 )): s[1][1] = '6'
        if (self.m_button12.BackgroundColour == wx.Colour( 255, 0, 0 )): s[1][2] = '6'
        if (self.m_button13.BackgroundColour == wx.Colour( 255, 0, 0 )): s[1][3] = '6'
        if (self.m_button14.BackgroundColour == wx.Colour( 255, 0, 0 )): s[1][4] = '6'

        if (self.m_button20.BackgroundColour == wx.Colour( 255, 0, 0 )): s[2][0] = '6'
        if (self.m_button21.BackgroundColour == wx.Colour( 255, 0, 0 )): s[2][1] = '6'
        if (self.m_button22.BackgroundColour == wx.Colour( 255, 0, 0 )): s[2][2] = '6'
        if (self.m_button23.BackgroundColour == wx.Colour( 255, 0, 0 )): s[2][3] = '6'
        if (self.m_button24.BackgroundColour == wx.Colour( 255, 0, 0 )): s[2][4] = '6'

        if (self.m_button30.BackgroundColour == wx.Colour( 255, 0, 0 )): s[3][0] = '6'
        if (self.m_button31.BackgroundColour == wx.Colour( 255, 0, 0 )): s[3][1] = '6'
        if (self.m_button32.BackgroundColour == wx.Colour( 255, 0, 0 )): s[3][2] = '6'
        if (self.m_button33.BackgroundColour == wx.Colour( 255, 0, 0 )): s[3][3] = '6'
        if (self.m_button34.BackgroundColour == wx.Colour( 255, 0, 0 )): s[3][4] = '6'

        if (self.m_button40.BackgroundColour == wx.Colour( 255, 0, 0 )): s[4][0] = '6'
        if (self.m_button41.BackgroundColour == wx.Colour( 255, 0, 0 )): s[4][1] = '6'
        if (self.m_button42.BackgroundColour == wx.Colour( 255, 0, 0 )): s[4][2] = '6'
        if (self.m_button43.BackgroundColour == wx.Colour( 255, 0, 0 )): s[4][3] = '6'
        if (self.m_button44.BackgroundColour == wx.Colour( 255, 0, 0 )): s[4][4] = '6'

        dispStr = \
            s[0][0] + s[0][1] + s[0][2] + s[0][3] + s[0][4] + ':' +\
            s[1][0] + s[1][1] + s[1][2] + s[1][3] + s[1][4] + ':' +\
            s[2][0] + s[2][1] + s[2][2] + s[2][3] + s[2][4] + ':' +\
            s[3][0] + s[3][1] + s[3][2] + s[3][3] + s[3][4] + ':' +\
            s[4][0] + s[4][1] + s[4][2] + s[4][3] + s[4][4]
        return dispStr

    def OnMenuSaveSelect( self, event ):
        with wx.FileDialog(self, "Save json file", wildcard="XYZ files (*.json)|*.json",
                        style=wx.FD_SAVE | wx.FD_OVERWRITE_PROMPT) as fileDialog:

            if fileDialog.ShowModal() == wx.ID_CANCEL:
                return

            pathname = fileDialog.GetPath()
            try:
                with open(pathname, 'w') as file:
                    s = self.getDisplayString()
                    print(s)
                    d = {}
                    d["anim01"] = s
                    str_ = json.dumps(d)
                    file.write(str_)
            except IOError:
                wx.LogError("Cannot save current data in file '%s'." % pathname)
    
    def OnMenuQuitSelect( self, event ):
        quit()

    def OnMenuOpenSelect( self, event):
        with wx.FileDialog(self, "Open json file", wildcard="json files (*.json)|*.json",
                        style=wx.FD_OPEN ) as fileDialog:

            if fileDialog.ShowModal() == wx.ID_CANCEL:
                return

            pathname = fileDialog.GetPath()
            try:
                with open(pathname, 'r') as f:
                    data = json.load(f)
                i = []
                i = data["anim01"].split(':')

                self.m_button00.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button01.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button02.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button03.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button04.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button10.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button11.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button12.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button13.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button14.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button20.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button21.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button22.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button23.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button24.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button30.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button31.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button32.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button33.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button34.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button40.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button41.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button42.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button43.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button44.SetBackgroundColour(wx.Colour( 0, 0, 0 ))

                if i[0][0] == '1': self.m_button00.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[0][1] == '1': self.m_button01.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[0][2] == '1': self.m_button02.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[0][3] == '1': self.m_button03.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[0][4] == '1': self.m_button04.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[1][0] == '1': self.m_button10.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[1][1] == '1': self.m_button11.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[1][2] == '1': self.m_button12.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[1][3] == '1': self.m_button13.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[1][4] == '1': self.m_button14.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[2][0] == '1': self.m_button20.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[2][1] == '1': self.m_button21.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[2][2] == '1': self.m_button22.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[2][3] == '1': self.m_button23.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[2][4] == '1': self.m_button24.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[3][0] == '1': self.m_button30.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[3][1] == '1': self.m_button31.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[3][2] == '1': self.m_button32.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[3][3] == '1': self.m_button33.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[3][4] == '1': self.m_button34.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[4][0] == '1': self.m_button40.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[4][1] == '1': self.m_button41.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[4][2] == '1': self.m_button42.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[4][3] == '1': self.m_button43.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[4][4] == '1': self.m_button44.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                
            except IOError:
                wx.LogError("Cannot open current data in file '%s'." % pathname)

    def OnExportPythonSelect( self, event ):
        anim = self.getDisplayString()
        tmp = anim.split(":")
        
        anim00 = tmp[0]  + ":" + tmp[1]  + ":" + tmp[2]  + ":" + tmp[3]  + ":" + tmp[4]
        anim01 = "00000" + ":" + tmp[0]  + ":" + tmp[1]  + ":" + tmp[2]  + ":" + tmp[3]
        anim02 = "00000" + ":" + "00000" + ":" + tmp[0]  + ":" + tmp[1]  + ":" + tmp[2]
        anim03 = "00000" + ":" + "00000" + ":" + "00000" + ":" + tmp[0]  + ":" + tmp[1]
        anim04 = "00000" + ":" + "00000" + ":" + "00000" + ":" + "00000" + ":" + tmp[0]
        anim05 = "00000" + ":" + "00000" + ":" + "00000" + ":" + "00000" + ":" + "00000"
        anim06 = tmp[4]  + ":" + "00000" + ":" + "00000" + ":" + "00000" + ":" + "00000"
        anim07 = tmp[3]  + ":" + tmp[4]  + ":" + "00000" + ":" + "00000" + ":" + "00000"
        anim08 = tmp[2]  + ":" + tmp[3]  + ":" + tmp[4]  + ":" + "00000" + ":" + "00000"
        anim09 = tmp[1]  + ":" + tmp[2]  + ":" + tmp[3]  + ":" + tmp[4]  + ":" + "00000"


        anim00 = "anim00 = Image(\"" + anim00 + "\")"
        anim01 = "anim01 = Image(\"" + anim01 + "\")"
        anim02 = "anim02 = Image(\"" + anim02 + "\")"
        anim03 = "anim03 = Image(\"" + anim03 + "\")"
        anim04 = "anim04 = Image(\"" + anim04 + "\")"
        anim05 = "anim05 = Image(\"" + anim05 + "\")"
        anim06 = "anim06 = Image(\"" + anim06 + "\")"
        anim07 = "anim07 = Image(\"" + anim07 + "\")"
        anim08 = "anim08 = Image(\"" + anim08 + "\")"
        anim09 = "anim09 = Image(\"" + anim09 + "\")"


        print("from microbit import *")
        print(anim00)
        print(anim01)
        print(anim02)
        print(anim03)
        print(anim04)
        print(anim05)


        print("anim = [anim00, anim01, anim02, anim03, anim04, anim05]")
        print("display.show(anim, delay=200)")
        with wx.FileDialog(self, "Export Python code", wildcard="Python files (*.py)|*.py",
                        style=wx.FD_SAVE | wx.FD_OVERWRITE_PROMPT) as fileDialog:

            if fileDialog.ShowModal() == wx.ID_CANCEL:
                return

            pathname = fileDialog.GetPath()
            try:
                with open(pathname, 'w') as file:
                    file.writelines("from microbit import *\n")
                    file.writelines(anim00 + "\n")
                    file.writelines(anim01 + "\n")
                    file.writelines(anim02 + "\n")
                    file.writelines(anim03 + "\n")
                    file.writelines(anim04 + "\n")
                    file.writelines(anim05 + "\n")
                    file.writelines(anim06 + "\n")
                    file.writelines(anim07 + "\n")
                    file.writelines(anim08 + "\n")
                    file.writelines(anim09 + "\n")
                    file.writelines("anim = [\n")
                    file.writelines("    anim00, anim01, anim02, anim03, anim04, anim05, anim06,\n")
                    file.writelines("    anim07, anim08, anim09]\n")
                    file.writelines("while True:\n")
                    file.writelines("    display.show(anim, delay=200)\n")
            except IOError:
                wx.LogError("Cannot save current data in file '%s'." % pathname)
