"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import microbitAnim
import json

# Implementing MyFrame1
class MyProject1MyFrame1( microbitAnim.MyFrame1 ):
    def __init__( self, parent ):
        microbitAnim.MyFrame1.__init__( self, parent )

    # Handlers for MyFrame1 events.
    def onButton00Click( self, event ):
        if (self.m_button00.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button00.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button00.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()
    
    def onButton01Click( self, event ):
        if (self.m_button01.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button01.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button01.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton02Click( self, event ):
        if (self.m_button02.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button02.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button02.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton03Click( self, event ):
        if (self.m_button03.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button03.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button03.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton04Click( self, event ):
        if (self.m_button04.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button04.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button04.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()


###
    def onButton10Click( self, event ):
        if (self.m_button10.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button10.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button10.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()
    
    def onButton11Click( self, event ):
        if (self.m_button11.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button11.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button11.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton12Click( self, event ):
        if (self.m_button12.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button12.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button12.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton13Click( self, event ):
        if (self.m_button13.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button13.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button13.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton14Click( self, event ):
        if (self.m_button14.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button14.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button14.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()
###
    def onButton20Click( self, event ):
        if (self.m_button20.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button20.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button20.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()
    
    def onButton21Click( self, event ):
        if (self.m_button21.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button21.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button21.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton22Click( self, event ):
        if (self.m_button22.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button22.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button22.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton23Click( self, event ):
        if (self.m_button23.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button23.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button23.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton24Click( self, event ):
        if (self.m_button24.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button24.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button24.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()
###
    def onButton30Click( self, event ):
        if (self.m_button30.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button30.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button30.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()
    
    def onButton31Click( self, event ):
        if (self.m_button31.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button31.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button31.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton32Click( self, event ):
        if (self.m_button32.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button32.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button32.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton33Click( self, event ):
        if (self.m_button33.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button33.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button33.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton34Click( self, event ):
        if (self.m_button34.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button34.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button34.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()
###
    def onButton40Click( self, event ):
        if (self.m_button40.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button40.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button40.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()
    
    def onButton41Click( self, event ):
        if (self.m_button41.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button41.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button41.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton42Click( self, event ):
        if (self.m_button42.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button42.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button42.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton43Click( self, event ):
        if (self.m_button43.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button43.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button43.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()

    def onButton44Click( self, event ):
        if (self.m_button44.BackgroundColour == wx.Colour( 255, 0, 0 )):
            self.m_button44.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
        else:
            self.m_button44.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
        event.Skip()
    
    def OnMenuSaveSelect( self, event ):
        s = ''
        if (self.m_button00.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button01.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button02.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button03.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button04.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button10.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button11.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button12.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button13.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button14.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button20.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button21.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button22.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button23.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button24.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button30.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button31.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button32.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button33.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button34.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button40.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button41.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button42.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button43.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        if (self.m_button44.BackgroundColour == wx.Colour( 255, 0, 0 )):
            s += '1'
        else:
            s += '0'
        print(s)


        # TODO: Implement OnMenuSaveSelect
        pass
    
    def OnMenuQuitSelect( self, event ):
        quit()

    def OnMenuOpenSelect( self, event):
        with wx.FileDialog(self, "Open json file", wildcard="json files (*.json)|*.json",
                        style=wx.FD_OPEN ) as fileDialog:

            if fileDialog.ShowModal() == wx.ID_CANCEL:
                return

            pathname = fileDialog.GetPath()
            try:
                with open(pathname, 'r') as f:
                    data = json.load(f)
                i = []
                i = data["anim01"].split(':')

                self.m_button00.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button01.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button02.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button03.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button04.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button10.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button11.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button12.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button13.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button14.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button20.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button21.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button22.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button23.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button24.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button30.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button31.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button32.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button33.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button34.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button40.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button41.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button42.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button43.SetBackgroundColour(wx.Colour( 0, 0, 0 ))
                self.m_button44.SetBackgroundColour(wx.Colour( 0, 0, 0 ))

                if i[0][0] == '1':
                    self.m_button00.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[0][1] == '1':
                    self.m_button01.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[0][2] == '1':
                    self.m_button02.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[0][3] == '1':
                    self.m_button03.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[0][4] == '1':
                    self.m_button04.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[1][0] == '1':
                    self.m_button10.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[1][1] == '1':
                    self.m_button11.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[1][2] == '1':
                    self.m_button12.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[1][3] == '1':
                    self.m_button13.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[1][4] == '1':
                    self.m_button14.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[2][0] == '1':
                    self.m_button20.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[2][1] == '1':
                    self.m_button21.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[2][2] == '1':
                    self.m_button22.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[2][3] == '1':
                    self.m_button23.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[2][4] == '1':
                    self.m_button24.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[3][0] == '1':
                    self.m_button30.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[3][1] == '1':
                    self.m_button31.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[3][2] == '1':
                    self.m_button32.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[3][3] == '1':
                    self.m_button33.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[3][4] == '1':
                    self.m_button34.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[4][0] == '1':
                    self.m_button40.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[4][1] == '1':
                    self.m_button41.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[4][2] == '1':
                    self.m_button42.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[4][3] == '1':
                    self.m_button43.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                if i[4][4] == '1':
                    self.m_button44.SetBackgroundColour(wx.Colour( 255, 0, 0 ))
                
            except IOError:
                wx.LogError("Cannot open current data in file '%s'." % pathname)